# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-27 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0002_auto_20171023_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
