# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0003_idea_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='available_fund',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='needed_fund',
            field=models.IntegerField(default=0),
        ),
    ]
