# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0005_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='idea',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vidiyal.Idea'),
        ),
    ]
