# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-02 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0006_issue_idea'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='idea',
        ),
        migrations.AddField(
            model_name='idea',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vidiyal.Issue'),
        ),
    ]
