# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0010_idea_img_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vidiyal.Issue'),
        ),
    ]
