# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-05 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidiyal', '0011_auto_20171105_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
